name: vienna_is
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^8.1.0
  flutter_typeahead: ^4.8.0
  get: ^4.6.5
  getwidget: ^4.0.0
  google_fonts: ^4.0.4
  lottie: ^2.3.2
  pluto_grid: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
